package dev.voigon.bootstrapper;

import lombok.Getter;

import java.io.*;
import java.time.Instant;
import java.util.Properties;

@Getter
public class BootstrapperConfiguration {

    public static BootstrapperConfiguration load(File file) throws IOException {
        Properties properties = new Properties();
        loadProperties(file, properties);
        return new BootstrapperConfiguration(properties);
    }

    /**
     * Specifies the main jar file name for the application
     */
    private final String mainJarFileName;

    private BootstrapperConfiguration(Properties properties) {
        this.mainJarFileName = properties.getProperty("mainJarFileName", "application.jar");

    }

    private static void loadProperties(File file, Properties properties) throws IOException {
        if (!file.exists()) {
            InputStream defaultPropertiesFile = Main.class.getClassLoader().getResourceAsStream("bootstrapper.properties");
            properties.load(defaultPropertiesFile);
            properties.store(new FileWriter(file), String.format("Generated by JavaBootstrapper version %s at %s", VersionInformation.VERSION, Instant.now()));
        } else
            properties.load(new FileInputStream(file));

    }
}
